### ISSUE TITLE
Mapping data to a dictionary from yaml file

### ISSUE THREAD

**Issue by neildobson-au** [danielgerlag/workflow-core#517]
According to https://workflow-core.readthedocs.io/en/latest/json-yaml/

**You can also pass object graphs to step inputs as opposed to just scalar values**

So is it possible to map to a step input parameter as a `Dictionary<string, string>`?

Here's my step:

``` csharp
public class UpdateAppConfigFileStep : StepBody
{
    // Inputs
    public string FileName { get; set; }
    public Dictionary<string, string> AppSettings { get; set; } = new Dictionary<string, string>();

    public override ExecutionResult Run(IStepExecutionContext context)
    {
        // Impl
        return ExecutionResult.Next();
    }
}
```

And a fragment of my yaml file

``` yaml
Id: Test
Version: 1
DataType: CI.Context, CI
Steps:
- Id: UpdateConfig
  StepType: CI.Steps.UpdateAppConfigFileStep, CI
  Inputs:
    FileName: data.ConfigFile
    AppSettings:
      'Connection': data.Connection
      'Default': data.Default
  NextStepId: RunApp
```

This currently throws:

**Object of type 'Newtonsoft.Json.Linq.JObject' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'**
