### ISSUE TITLE
Question: How to pass a multi-line string as an input property in a YAML workflow?

### ISSUE THREAD

**Issue by bbollard** [danielgerlag/workflow-core#633]
I have been trying without success to create a YAML workflow definition that includes nicely formatted human readable text that appear on multiple lines. Here is an example of what I am trying to do, can anyone please point me to the right syntax?

```yaml
Id: HelloWorld
Version: 1
Steps:
- Id: MyStep
  StepType: WorkflowStep, MyStep
  NextStepId: ...
  Inputs:
    TextToProcess: 
                    This is my multiple line text
                    That I would like to
                    Pass as the input to the
                    'TextToProcess' Input Parameter

    Title: '"The Title"'
```

Thanks for your assistance!

**Comment by tingwei628** [comment]
@bbollard  [How do I break a string over multiple lines?](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines)

**Comment by bbollard** [comment]
@tingwei628 

I reviewed that and proved that the SharpYaml engine will properly interpret this:

```yaml
Id: HelloWorld
Version: 1
Steps:
- Id: MyStep
  StepType: WorkflowStep, MyStep
  NextStepId: ...
  Inputs:
    Script: |
                Get-Date
                dir c:\

    Title: '"The Title"'
```

But LoadDefinition will throw an exception. I think there is some extra processing going on by the LoadDefinition engine to walk the YAML and build a workflow dynamically from it and as part of that there is some evaluation of the multiline value that is failing with exception "System.Linq.Dynamic.Core.Exceptions.ParseException: 'Unknown identifier 'Get''" at this line:

```csharp
var sourceExpr = DynamicExpressionParser.ParseLambda(new[] { dataParameter, contextParameter, environmentVarsParameter }, typeof(object), expr);
```
