### ISSUE TITLE
how to get publish event data?

### ISSUE THREAD

**Issue by netcore-jroger** [danielgerlag/workflow-core#642]
how to get publish event data?

**Comment by Tesagi** [comment]
@netcore-jroger, if u mean in access to event data in step, then IStepExecutionContext.ExecutionPointer.EventData

**Comment by netcore-jroger** [comment]
I have an other question.can you help me?

**Comment by Tesagi** [comment]
i try :)

**Comment by netcore-jroger** [comment]
My dsl like this:
file name `hello-flow.yml`
```yaml
Id: e24d66b7-f97b-41b3-bd27-b16c4345f8db
Version: 1
DataType: A.Application.Flow.FlowData, A.Application
Steps:
  - Id: step1
    StepType: A.Application.Flow.Steps.StartStep, A.Application
    NextStepId: step2
    Inputs:
      UserId: "data.UserId"
  - Id: step2
    StepType: A.Application.Flow.Steps.ApprovalStep, A.Application
    NextStepId: step3
  - Id: step3
    StepType: A.Application.Flow.Steps.StopStep, A.Application
    Inputs:
      UserId: "data.UserId"
```

```csharp
    public class StartStep : StepBodyAsync
    {
        private readonly ILogger<StartStep> _logger;

        public StartStep(
            ILogger<StartStep> logger
        )
        {
            this._logger = logger;
        }

        public Guid UserId { get; set; }

        public override Task<ExecutionResult> RunAsync(IStepExecutionContext context)
        {
            // log start event.
            this._logger.LogWarning($"用户：{this.UserId} 发起了审批");
            return Task.FromResult(ExecutionResult.Next());
        }
    }

    public class StopStep : StepBodyAsync
    {
        private readonly ILogger<StartStep> _logger;

        public StopStep(
            ILogger<StartStep> logger
        )
        {
            this._logger = logger;
        }

        public Guid UserId { get; set; }

        public override Task<ExecutionResult> RunAsync(IStepExecutionContext context)
        {
            // log start event.
            this._logger.LogWarning($"用户：{this.UserId} 的审批结束");
            return Task.FromResult(ExecutionResult.Next());
        }
    }

    public class ApprovalStep : StepBodyAsync
    {
        public override async Task<ExecutionResult> RunAsync(IStepExecutionContext context)
        {
            if ( !context.ExecutionPointer.EventPublished )
            {
                return ExecutionResult.WaitForEvent("abc", "abc", DateTime.MinValue);
            }

            await Task.Yield();

            return ExecutionResult.Next();
        }
    }
```

```csharp
// one webapi start workflow
            var dsl = await System.IO.File.ReadAllTextAsync(@"hello-flow.yml", Encoding.UTF8, cancellationToken);
            var definition = this._definitionLoader.LoadDefinition(dsl, Deserializers.Yaml);

            var initialData = new FlowData {
                UserId = Guid.Empty
            };
            var result = await this._workflowHost.StartWorkflow(definition.Id, definition.Version, initialData);
```

```csharp
// an other webapi publish event
await this._workflowHost.PublishEvent("abc", "abc", eventData);
```
